### ISSUE TITLE
support SSH

### ISSUE THREAD

**Issue by frct1** [schroffl/teamspeak-query#13]
Hi @schroffl teamspeak are showed SSH protocol for server query (server 3.3.0v Beta). Do you will update lib for work with this ?

**Comment by schroffl** [comment]
Can you please send me a link to the changelog and some information about the update?
If I can get my hands on the beta server I will check it out and try to implement it.

**Edit**: I found [the changelog](https://forum.teamspeak.com/threads/136231-PreRelease-TeamSpeak-3-Server-3-3-0-Beta)

**Comment by frct1** [comment]
i think [this package ssh2](https://www.npmjs.com/package/ssh2) will be useful for support ssh

**Comment by schroffl** [comment]
Thank you, I will take a look at it :)

**Comment by schroffl** [comment]
Published in [`v3.0.0`](https://github.com/schroffl/teamspeak-query/releases/tag/v3.0.0).
