### ISSUE TITLE
Optional file upload

### ISSUE THREAD

**Issue by lusu007** [schroffl/teamspeak-query#16]
Hey @schroffl ,

I would really appreciate it if you would implement something to upload files.
It's a pain in the butt to upload something like an icon to a TeamSpeak Server with a Javascript application.

Thank you in advance,
Lukas Jost

**Comment by frct1** [comment]
Hi @lusu007. You should use https://github.com/schroffl/teamspeak-filesystem
Work perfectly

**Comment by lusu007** [comment]
Oh okay thank you @bigHapiness .

**Comment by schroffl** [comment]
@bigHapiness Thank you for taking care of some of the issues, I really appreciate it :)

@lusu007 If you have any suggestions or questions regarding the file-package feel free to tell/ask me in a new issue :)
