### ISSUE TITLE
notifyclientmoved not working

### ISSUE THREAD

**Issue by timoschuetz** [schroffl/teamspeak-query#21]
Hello,
I'm currently on writing a bot and I cannot use the notifyclientmoved notify. I call the servernotifyregister right after the one for the server and both should be triggered through their .on function. 

```javascript
const connect =  con.query.send('use', 1)
  .then(() => con.query.send('clientupdate', {'client_nickname':opt.botname}))
  .then(() => con.query.send('servernotifyregister', { 'event': 'server' }))
  .then(() => con.query.send('servernotifyregister', { 'event': 'channel', 'id': '1'} ))
  .then(() => console.log('Done! Everything went fine'))
  .catch(err => console.error('An error occured:', err))



con.query.on('cliententerview', data =>{
  console.log(data.client_nickname, 'connected');
  func.sendmessage(data.clid);
}) //this one works

con.query.on('notifyclientmoved', data =>{
  console.log(data, 'channel');
  console.log(data);
}) //this doesn't
 ```

**Comment by schroffl** [comment]
I'm not sure if I remember correctly, but if I do, this is the reason:  
Because `notifyclientmoved` is a channel-event you will only get notified about it if the bot is actually in the same channel where the event was fired. Would you mind checking whether that works?

**Comment by timoschuetz** [comment]
I double checked it and it works in the ssh query without any problems, but not with the libary. I tried to get the query client to join a channel, but it won't do that.

**Comment by schroffl** [comment]
Oh alright, I will take a look at it then :)

**Comment by schroffl** [comment]
Hey, I didn't forget about you, it's just rather stressful at work right now.
I will tackle this on friday :)

**Comment by timoschuetz** [comment]
Thanks, Take the time you need..

-------- Original-Nachricht --------
An 20. Nov. 2018, 13:03, schroffl schrieb:

**Comment by schroffl** [comment]
I just noticed why it doesn't work. You listen to `notifyclientmoved`, but should instead listen to `clientmoved`, because the `notify` [is removed from the event string](https://github.com/schroffl/teamspeak-query/blob/master/lib/base.js#L116). 
I should probably add some documentation regarding the events.

**Comment by timoschuetz** [comment]
Yeah,

That could have been the problem. Thanks for your help. I will try it as soon as I can

-------- Original-Nachricht --------
An 26. Nov. 2018, 20:43, schroffl schrieb:

**Comment by schroffl** [comment]
Did it work?

**Comment by timoschuetz** [comment]
Yep, it's working now ;D

**Comment by schroffl** [comment]
Great, glad to hear that :)
