### ISSUE TITLE
Response style

### ISSUE THREAD

**Issue by frct1** [schroffl/teamspeak-query#3]
Hi, **schroffl** yesterday i'm met with your library, it's awesome, but have an problem.
How to get command with one mere elements (serverlist for example) output [like this](https://gist.github.com/bigHapiness/9524835567bb0c1c93b60a5ef1f42021), because not very comfortable to work [with output like this](https://gist.github.com/bigHapiness/4dfa681c68a957b54b5ebdf67eea8afc).
Last library which i was work it is `node-teamspeak` thats return response [this](https://gist.github.com/bigHapiness/9524835567bb0c1c93b60a5ef1f42021).

**Comment by schroffl** [comment]
Could you please add the raw response of the server? I can't test it myself right now since I'm in the process of reinstalling Windows. 

As for the issue, I was thinking of letting users pass custom parsers for certain commands.
Maybe something along the lines of this:
```javascript
function myParser(str) {
  // Do some parsing
  return data;
}

const TeamspeakQuery = require('teamspeak-query');
const query = new TeamspeakQuery('127.0.0.1', 10011);

query.send('login', 'serveradmin', 'changeme')
  .then(() => query.send(myParser, 'serverlist'))
  .then(console.log);
```

If one needs to run a command with a specific parser frequently, some javascript-magic could be applied:
```javascript
const niceSend = query.send.bind(query, myParser);

// use it
query.send('login', 'serveradmin', 'changeme')
  .then(() => niceSend('serverlist'))
  .then(() => niceSend('some other command'))
  .then(() => niceSend('some other other command'));
```

Common parsers for a case like yours could be added to the library.

**Comment by frct1** [comment]
```
<Removed>
```
or privilegekeylist command
```
<Removed>
```
Thank you for fast answer 

**Edit (schroffl)**: I removed the output of the two commands, just in case it contained any confidential data.

**Comment by schroffl** [comment]
Hey,

I am currently not really sure why I parse responses as if it had this syntax:
`virtualserver_id=4|9 virtualserver_port=9950|9987` (multiple values being specified for the same property) etc.
Do you know of any command where this might be the case? If not, I could just split by `|` and parse each entry in that list.

**Comment by frct1** [comment]
Hi, I think command `snapshotcreate` that what you need, but in both libraries I used was a strange parsed output of the result of this command.
In the library which I used it was just such a parsing (split by `|` and parse each entry), since there might be several elements in the response from the server.

**Comment by schroffl** [comment]
`snapshotcreate` doesn't seem to be properly parsable with either method. It has too many inconsistencies.
However, the `parseList` function in this snippet should be sufficient to produce a nice output of commands like `clientdblist`, `clientlist`, etc. and work with the current version of the library.
```javascript
const TeamspeakQuery = require('teamspeak-query');
const query = new TeamspeakQuery('127.0.0.1', 10011);

function parseList(data) {
  return data.raw()
    .split('|')
    .map(TeamspeakQuery.parse)
    .map(entry => entry.params);
}

query.send('login', 'serveradmin', 'changeme')
  .then(() => query.send('use', 1))
  .then(() => query.send('clientdblist'))
  .then(parseList)
  .then(console.log)
  .catch(console.error);
```

and if you use that pattern a few times you can create a small helper function

```javascript
function sendList() {
  return query.send.apply(query, Array.from(arguments)).then(parseList);
}

query.send('login', 'serveradmin', 'changeme')
  .then(() => query.send('use', 1))
  .then(() => sendList('clientdblist'))
  .then(() => sendList('clientlist'))
  .then(console.log)
  .catch(console.error);
```
I would prefer to keep the core library as concise as possible and only expose a simple and clean API.
And if anybody ever needs to do some custom parsing, they can do so by calling the `raw` function of the response object (which I forgot to document, but will do now) to obtain the plaintext.

**Comment by frct1** [comment]
Oh, check the bug, if output will parse by custom function in every element have raw data of server response.

**Comment by schroffl** [comment]
This is a result of mapping [`TeamspeakQuery.parse`](https://github.com/schroffl/teamspeak-query#teamspeakqueryparsestr) over the array that was created by splitting the string.
If you don't want it you can update your `parseList` function to look like this:
```javascript
function parseList(data) {
  return data.raw()
    .split('|')
    .map(TeamspeakQuery.parse)
    .map(entry => entry.params)
    .map(entry => {
      delete entry.raw;
      return entry;
    });
}
```
or if you want to keep it small
```javascript
function parseList(data) {
  return data.raw()
    .split('|')
    .map(TeamspeakQuery.parse)
    .map(entry => entry.params)
    .map(entry => (delete entry.raw, entry));
}
```

**Comment by frct1** [comment]
Ok, I have the last question when I try to connect to several instances by getting a list of servers from the api (returning object with data of every server instance), then there is a problem that connects only to one server.
But if you specify a list of servers at the beginning of the application, then all connections to the described servers are successful.

**Comment by schroffl** [comment]
Could you add a small example? I'm not really sure what you mean.

**Comment by frct1** [comment]
Hi, @schroffl.
Yes, sure, [that's example](https://gist.github.com/bigHapiness/061b077efe494525ce0f3358591cc535) with **server list, which described in applicaton**.
That's [second example ](https://gist.github.com/bigHapiness/8babdb7c0723516d21f125ade627ad6c)**with billing api usage**

**Comment by schroffl** [comment]
I don't see any problems in your code. Do you get any network errors while trying to connect? Are you sure that you are using the correct ip and port for your servers?

**Comment by frct1** [comment]
Nope, haven't any errors. In api response same object, which was write in first example.
Buuuuut first example working, and second no 🤔
I'm can send you data of testing instances, via e-mail or messenger

**Comment by schroffl** [comment]
You can send it to this email: schroffl@users.noreply.github.com
Just leave a comment when you send it, because I'm not entirely sure if this email works ^^

**Comment by frct1** [comment]
Heh, okay, I prepare the instances and send the data for connection.

**Comment by schroffl** [comment]
Doesn't seem to have worked, can you try this one: \<removed\>

**Comment by frct1** [comment]
Successful send data about instances to \<removed\>

**Comment by schroffl** [comment]
Resolved via e-mail
