### ISSUE TITLE
Handling network/socket errors

### ISSUE THREAD

**Issue by frct1** [schroffl/teamspeak-query#4]
Hi, @schroffl.
I forgot to say about error handling and also authorize only if you successfully connect to the Server Query interface.
I realized it myself, I hope this code is correctly written.
"index.js" of teamspeak-query lib.
```javascript
                let self=this;
                sock.on('connect', () => {
			this.carrier = carrier.carry(sock);
			this.carrier.on('line', this.handleLine.bind(this));
			self.emit('connect');//Send event after successful connect to SQ
		});
		sock.on("error", function(err){
			self.emit("error", err);//Send error event to code
		});
```

Handling error directly in code or connect if we get an `connect` event
```javascript
query.on('error', function (err) {
                if (err.address && err.port) {
                    console.log('Error on connect [ ' +err.code +'] '+err.address + ':' + err.port);
                 }
            });
query.on('connect',function () {
                query.send('login', username, password)
                    .then(function () {
                        console.log('OK');
                    }).catch(function (error) {
                    console.log(error);
                });
            });
```
I hope my code does not look like shit 😆

**Edit (schroffl):** Syntax highlighting

**Comment by schroffl** [comment]
The socket is already being assigned to the `sock` property in the constructor ([See Line 25](https://github.com/schroffl/teamspeak-query/blob/master/index.js#L25)).
I'm not sure if this works, but you can give it a shot:

```javascript
let query = new TeamspeakQuery(ip, port);

query.sock.on('connect', () => console.log('I am connected'));
query.sock.on('error', err => console.error('Oh no:', err));

// Commands are sent only once we are connected anways, so
// you shouldn't have to put this in the 'connect' event handler
query.send('login', 'username', 'password');
```

If it doesn't, just tell me and I will take a look at it.

**Comment by frct1** [comment]
It works well, thanks 👍
Before I didn't know about error handling is already included in the net library **^ _ ^**

**Comment by schroffl** [comment]
Glad to hear :)
I changed the title so other people can hopefully find it easier when they are experiencing issues with their connection.
